# Generated by Django 2.0 on 2020-06-19 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField()),
                ('uniqueTempKey', models.CharField(default='myNull', max_length=200)),
                ('saleDocLink', models.URLField(blank=True, null=True)),
                ('salePointsCreated', models.NullBooleanField()),
                ('researchDone', models.NullBooleanField()),
                ('internalMeetingCreated', models.NullBooleanField()),
            ],
        ),
    ]
