# Generated by Django 2.0 on 2020-06-19 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='added_to_google_calendar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='meetings',
            name='added_to_google_calendar',
            field=models.BooleanField(default=False),
        ),
    ]
